In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [13]:
def cargaAlcaldes(archivo, columna, fila, cabecera, nombreHoja):
    return pd.read_excel(archivo, sheet_name=nombreHoja,
         names=cabecera, usecols=columna, skiprows=fila)

directorio = "/Users/oscar.torresrodrigue/Downloads/alcaldes/"
nombre_archivos = [ [directorio + "Alcaldes_Mandato_1979_1983.xlsx", "D:K", 8, 
                     ['CCAA', 'PROVINCIA', 'MUNICIPIO', 'CÓDIGO', 'NOMBRE', 'LISTA', 'FECHA-POSESION', 'FECHA-BAJA'], 'Alcaldes 1979-1983'],
                    [directorio + "Alcaldes_Mandato_1983_1987.xlsx", "D:K", 8, 
                     ['CCAA', 'PROVINCIA', 'MUNICIPIO', 'CÓDIGO', 'NOMBRE', 'LISTA', 'FECHA-POSESION', 'FECHA-BAJA'], 'Alcaldes 1983-1987'],
                    [directorio + "Alcaldes_Mandato_1987_1991.xlsx", "D:K", 8, 
                     ['CCAA', 'PROVINCIA', 'MUNICIPIO', 'CÓDIGO', 'NOMBRE', 'LISTA', 'FECHA-POSESION', 'FECHA-BAJA'], 'Alcaldes 1987-1991'],
                    [directorio + "Alcaldes_Mandato_1991_1995.xlsx", "D:K", 8, 
                     ['CCAA', 'PROVINCIA', 'MUNICIPIO', 'CÓDIGO', 'NOMBRE', 'LISTA', 'FECHA-POSESION', 'FECHA-BAJA'], 'Alcaldes 1991-1995'],
                    [directorio + "Alcaldes_Mandato_1995_1999.xlsx", "D:K", 8, 
                     ['CCAA', 'PROVINCIA', 'MUNICIPIO', 'CÓDIGO', 'NOMBRE', 'LISTA', 'FECHA-POSESION', 'FECHA-BAJA'], 'Alcaldes 1995-1999'],
                    [directorio + "Alcaldes_Mandato_1999_2003.xlsx", "D:K", 8, 
                     ['CCAA', 'PROVINCIA', 'MUNICIPIO', 'CÓDIGO', 'NOMBRE', 'LISTA', 'FECHA-POSESION', 'FECHA-BAJA'], 'Alcaldes 1999-2003'],
                    [directorio + "Alcaldes_Mandato_2003_2007.xlsx", "D:K", 8, 
                     ['CCAA', 'PROVINCIA', 'MUNICIPIO', 'CÓDIGO', 'NOMBRE', 'LISTA', 'FECHA-POSESION', 'FECHA-BAJA'], 'Alcaldes 2003-2007'],
                    [directorio + "Alcaldes_Mandato_2007_2011.xlsx", "D:K", 8, 
                     ['CCAA', 'PROVINCIA', 'MUNICIPIO', 'CÓDIGO', 'NOMBRE', 'LISTA', 'FECHA-POSESION', 'FECHA-BAJA'], 'Alcaldes 2007-2011'],
                    [directorio + "Alcaldes_Mandato_2011_2015.xlsx", "D:K", 8, 
                     ['CCAA', 'PROVINCIA', 'MUNICIPIO', 'CÓDIGO', 'NOMBRE', 'LISTA', 'FECHA-POSESION', 'FECHA-BAJA'], 'Alcaldes 2011-2015'],
                    [directorio + "Alcaldes_Mandato_2015_2019.xlsx", "D:K", 8, 
                     ['CCAA', 'PROVINCIA', 'MUNICIPIO', 'CÓDIGO', 'NOMBRE', 'LISTA', 'FECHA-POSESION', 'FECHA-BAJA'], 'Alcaldes 2015-2019'],
                    [directorio + "Alcaldes_Mandato_2019_2023.xlsx", "D:K", 8, 
                     ['CCAA', 'PROVINCIA', 'MUNICIPIO', 'CÓDIGO', 'NOMBRE', 'LISTA', 'FECHA-POSESION', 'FECHA-BAJA'], 'Alcaldes 2015-2019']
                    ]


#Inicialización do dataframe vacío
dfAlcaldes = pd.DataFrame([])

for i in range(0, len(nombre_archivos)):
    dfAlcaldes = pd.concat([dfAlcaldes,
        cargaAlcaldes(nombre_archivos[i][0], nombre_archivos[i][1], 
            nombre_archivos[i][2], nombre_archivos[i][3], nombre_archivos[i][4])]
    )

dfAlcaldes

,CCAA,PROVINCIA,MUNICIPIO,CÓDIGO,NOMBRE,LISTA,FECHA-POSESION,FECHA-BAJA
0,Andalucía,Almería,ABRUCENA,040025,"MARTINEZ LAO, JUAN",PSOE,1979-04-19 00:00:00,NaT
1,Andalucía,Almería,ADRA,040031,"SARMIENTO POSADA, PEDRO",OTROS,1979-04-19 00:00:00,NaT
2,Andalucía,Almería,ALBANCHEZ,040046,"MARTOS AYBAR, RAMON",UCD,1979-04-19 00:00:00,NaT
3,Andalucía,Almería,ALBOLODUY,040059,"BLANES PANIAGUA, MARIANO",UCD,1979-04-19 00:00:00,NaT
4,Andalucía,Almería,ALBOX,040062,"MIRAS CARRASCO, JOSE",UCD,1979-04-19 00:00:00,NaT
...,...,...,...,...,...,...,...,...
8758,"Rioja, La","Rioja, La",Viniegra de Abajo,261780,Juan Ignacio Martínez Fernández,PP,15/06/2019,NaN
8759,"Rioja, La","Rioja, La",Viniegra de Arriba,261793,Laura Crespi Lázaro,PP,15/06/2019,NaN
8760,"Rioja, La","Rioja, La",Zarratón,261807,Víctor Manuel Manso Ocio,PSOE,15/06/2019,NaN
8761,"Rioja, La","Rioja, La",Zarzosa,261814,José María Sáenz Blanco,PP,15/06/2019,NaN
8762,"Rioja, La","Rioja, La",Zorraquín,261835,José Ángel Capellán Marín,PP,15/06/2019,NaN