# T3.2 Analizar e visualizar estatísticas de datos baixados de MongoDB
## Conexión a MongoDB dende Python e análise de datos

En Atlas mete o dataset de exemplo na túa base de datos.

Engade o enderezo IP autorizado a conectar para que poidas conectar á base de datos.

Proba a conectar dende compass coa URL de conexión que che da.

Da BBDD de proba: sample_mfix, na colección movies: https://www.mongodb.com/docs/atlas/sample-data/sample-mflix/

Conecta a Atlas dende Python, carga a colección en Pandas. Averigua o modo máis adecuado.

In [1]:
from pymongo import MongoClient

#HOST="(...).mongodb.net"
HOST="cluster0.frtdehn.mongodb.net"
PORT=27017
USERNAME="xuwira19"
PASSWORD="changeme1."

if HOST == 'localhost':
    if not USERNAME:
        cli_mongo = MongoClient(HOST, PORT)
    else:
        cli_mongo = MongoClient(HOST, PORT, USERNAME, PASSWORD)
else:
    cli_mongo = MongoClient(f"mongodb+srv://{USERNAME}:{PASSWORD}@{HOST}/test")

In [2]:
print(cli_mongo.list_database_names())

['covid', 'sample_airbnb', 'sample_analytics', 'sample_geospatial', 'sample_guides', 'sample_mflix', 'sample_restaurants', 'sample_supplies', 'sample_training', 'sample_weatherdata', 'admin', 'local']

### Cargar la bd de mongo a pandas

In [3]:
import pandas as pd

db_sample_flix=cli_mongo['sample_mflix']

cursor = db_sample_flix['movies'].find()

df = pd.DataFrame(list(cursor))

del df['_id']

df

,plot,genres,runtime,cast,poster,title,fullplot,languages,released,directors,...,awards,lastupdated,year,imdb,countries,type,tomatoes,num_mflix_comments,writers,metacritic
0,A group of bandits stage a brazen train hold-u...,"[Short, Western]",11.0,"[A.C. Abadie, Gilbert M. 'Broncho Billy' Ander...",https://m.media-amazon.com/images/M/MV5BMTU3Nj...,The Great Train Robbery,Among the earliest existing films in American ...,[English],1903-12-01,[Edwin S. Porter],...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-13 00:27:59.177000000,1903,"{'rating': 7.4, 'votes': 9847, 'id': 439}",[USA],movie,"{'viewer': {'rating': 3.7, 'numReviews': 2559,...",0,NaN,NaN
1,"A greedy tycoon decides, on a whim, to corner ...","[Short, Drama]",14.0,"[Frank Powell, Grace Henderson, James Kirkwood...",NaN,A Corner in Wheat,"A greedy tycoon decides, on a whim, to corner ...",[English],1909-12-13,[D.W. Griffith],...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-13 00:46:30.660000000,1909,"{'rating': 6.6, 'votes': 1375, 'id': 832}",[USA],movie,"{'viewer': {'rating': 3.6, 'numReviews': 109, ...",1,NaN,NaN
2,"Cartoon figures announce, via comic strip ball...","[Animation, Short, Comedy]",7.0,[Winsor McCay],https://m.media-amazon.com/images/M/MV5BYzg2Nj...,"Winsor McCay, the Famous Cartoonist of the N.Y...",Cartoonist Winsor McCay agrees to create a lar...,[English],1911-04-08,"[Winsor McCay, J. Stuart Blackton]",...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-29 01:09:03.030000000,1911,"{'rating': 7.3, 'votes': 1034, 'id': 1737}",[USA],movie,"{'viewer': {'rating': 3.4, 'numReviews': 89, '...",0,"[Winsor McCay (comic strip ""Little Nemo in Slu...",NaN
3,"A woman, with the aid of her police officer sw...","[Crime, Drama]",88.0,"[Jane Gail, Ethel Grandin, William H. Turner, ...",https://m.media-amazon.com/images/M/MV5BYzk0YW...,Traffic in Souls,NaN,[English],1913-11-24,[George Loane Tucker],...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-09-15 02:07:14.247000000,1913,"{'rating': 6.0, 'votes': 371, 'id': 3471}",[USA],movie,"{'viewer': {'rating': 3.0, 'numReviews': 85, '...",1,NaN,NaN
4,"The cartoonist, Winsor McCay, brings the Dinos...","[Animation, Short, Comedy]",12.0,"[Winsor McCay, George McManus, Roy L. McCardell]",https://m.media-amazon.com/images/M/MV5BMTQxNz...,Gertie the Dinosaur,Winsor Z. McCay bets another cartoonist that h...,[English],1914-09-15,[Winsor McCay],...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-18 01:03:15.313000000,1914,"{'rating': 7.3, 'votes': 1837, 'id': 4008}",[USA],movie,"{'viewer': {'rating': 3.7, 'numReviews': 29}, ...",0,[Winsor McCay],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21344,A-Gu enlists a group of contract killers in th...,[Comedy],110.0,"[Hsiao-chuan Chang, Qian Wan, Tang Sui, Yann Y...",NaN,The Laundryman,A-Gu enlists a group of contract killers in th...,[Mandarin],2015-07-11,[Chung Lee],...,"{'wins': 0, 'nominations': 2, 'text': '2 nomin...",2015-09-15 06:14:05.163000000,2015,"{'rating': 6.3, 'votes': 27, 'id': 4801514}",[Taiwan],movie,NaN,1,NaN,NaN
21345,"Karol, an ordinary young man, runs into a much...",[Thriller],90.0,"[Filip Plawiak, Adam Woronowicz, Julia Kijowsk...",NaN,The Red Spider,"Karol, an ordinary young man, runs into a much...","[Polish, English]",2015-11-20,[Marcin Koszalka],...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-08-18 00:52:59.093000000,2015,"{'rating': 7.4, 'votes': 16, 'id': 4817256}","[Poland, Czech Republic, Slovakia]",movie,NaN,0,"[Marcin Koszalka, Lukasz M. Maciejewski, Marta...",NaN
21346,Guy's tragic death is a shock for the Leblanc ...,[Drama],102.0,"[Maxim Gaudette, Karelle Tremblay, Valerie Cad...",NaN,Our Loved Ones,Guy's tragic death is a shock for the Leblanc ...,[French],2015-08-12,[Anne èmond],...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-08-27 00:18:43.727000000,2015,"{'rating': 7.4, 'votes': 5, 'id': 4881276}",[Canada],movie,NaN,0,[Anne èmond],NaN
21347,NaN,[Documentary],115.0,[Chantal Akerman],NaN,No Home Movie,NaN,[French],2015-08-10,[Chantal Akerman],...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-08-13 18:35:53.927000000,2015,"{'rating': 3.8, 'votes': 5, 'id': 4881016}","[Belgium, France]",movie,NaN,0,[Chantal Akerman],NaN
21348,"Sex and love. Some seek it, some need it, some...","[Comedy, Drama, Romance]",91.0,"[Holly Aird, Eileen Atkins, Hugh Bonneville, T...",https://m.media-amazon.com/images/M/MV5BMTA5OT...,Scenes of a Sexual Nature,Various Londeners meet people in Hampstead Hea...,[English],NaT,[Ed Blum],...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-09-12 09:51:28.903000000,2006,"{'rating': 6.1, 'votes': 4125, 'id': 475380}",[UK],movie,"{'website': 'http://www.tinpanfilms.com/', 'vi...",0,[Aschlin Ditta],NaN

A) Contar o total de películas.

In [4]:
df['title'].isna().sum()

len(df)

21349

B) Contar o número de películas de cada xénero.

In [5]:
#usar explode
genres = db_sample_flix['movies'].find({'genres':{'$all':['']}})
dfGenres = pd.DataFrame(list(genres))
dfGenres
# for i in df['genres']:
#     for j in i:
#         print(j)

Empty DataFrame
Columns: []
Index: []

C) Contar cantas películas hai por ano.

D) Mirar se hai correlación entre imdb e rotten tomatoes.

E) Contar cantas películas ten cada director

F) Contar en cantas películas ten participado cada actor

G) Contar cantas películas hai de cada idioma

H) Cal é a media de premios das películas

J) Amosar as películas que teñen alomenos 3 premios

K) Contar as películas por país